---

plugins:
  - jest

env:
  node: true
  jest: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 8
 
rules:
  no-console: 0
  import/extensions: 0
